### ISSUE TITLE
Friendly players buff not showing text

### ISSUE THREAD

**Issue by Viodith** [Resike/Z-Perl#179]
Friendly players buff bar is showing but no text about what buff it is ect. 
It worked in 7.3
![Skærmbillede 2024-08-17 050628](https://github.com/user-attachments/assets/c33edaf4-ff1c-4d23-b306-14efb6c987a4)
![Skærmbillede 2024-08-17 050744](https://github.com/user-attachments/assets/0e76b026-1959-4d6f-ac50-4342fc967aa6)
![Skærmbillede 2024-08-17 050808](https://github.com/user-attachments/assets/bf70a6c0-8533-463a-9ad0-4c024b6e2fba)

did i miss a option to click? because i have looked and looked and havent found one

**Comment by Zwyk** [comment]
Confirmed, tooltip from target buffs are not showing on Classic-SoD.
Debuffs are fine.
Other frames buffs and debuffs are fine.

Maybe linked to [Issue 176](https://github.com/Resike/Z-Perl/issues/176) but I think this was bugged before.

**Comment by trebunner** [comment]
Also having this issue on 7.3.4

**Comment by carlos93** [comment]
Should be fixed here https://github.com/Resike/Z-Perl/pull/182

**Comment by Lekandor** [comment]
Still not working for me. Even after the patch + reinstalling it.

**Comment by Viodith** [comment]
still not working for me

**Comment by GadyEilat** [comment]
Still not working. Buffs won't have their tooltip show on your target.

**Comment by trebunner** [comment]
Temporarily you can edit it yourself as the fix posted does work and is only 1 simple edit. Worked for me anyways, edit with notepad and search.

**Comment by GadyEilat** [comment]
> Temporarily you can edit it yourself as the fix posted does work and is only 1 simple edit. Worked for me anyways, edit with notepad and search.

How though?
Can you explain which file should we edit and where?

**Comment by carlos93** [comment]
No new patch has been deployed to curse forge i guess
