### ISSUE TITLE
Combo Points Switching With Every Target

### ISSUE THREAD

**Issue by Jackodawacko** [Resike/Z-Perl#8]
Hi there,

Currently when I'm adding combo points to my kill target and I click on a different target (or press Tab), the combo points switch over as well to the next target (without me adding combo points to them). It'll show the exact number of bubbles but when I try to use a finishing move on the other target (the one that had the combo points swapped to), nothing (which it shouldn't) happens but I'm able to swap back to my main target (one I built the combo points on) and use my finishing move. 

I've turned off Z-Perl and the combo points work fine after that with the switching and have talked to other rogues as well with this issue. I've gone ahead and recorded an example video in a PvE scenario (but the real issue comes within PvP which can really be confusing/more important).

Video: https://streamable.com/jj7671

Let me know if there's anything I can do/help with!

**Also side note:** Enemy debuff icon timers aren't "counting down" as in the picture used to do a clockwise dark overlay as each second ticks, giving you a visual timer. The only way to check is if you hover over the debuff and read the "X amount of seconds" till it's done. Example debuff I tested this on was power word shield debuff.

**Comment by Jackodawacko** [comment]
@Resike sorry, forgot to tag :D

**Comment by Resike** [comment]
Should be fixed with **6.2.1**, let me know if it works properly now or not.

**Comment by Jackodawacko** [comment]
The combo points are working properly now, you are awesome. The buffs/debuffs is still not working properly though. I will create a new ticket on GitHub for it. I've recorded a video (with commentary) showing what's going on.
